<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\Reservations\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\..\Availability\Contracts\Availability.Contracts.csproj" />
    <ProjectReference Include="..\..\Pricing\Contracts\Pricing.Contracts.csproj" />
  </ItemGroup>
</Project>
